import React, { useEffect, useMemo, useRef, useState } from "react";
import { apiClient } from "../services/api";
import { User, UserRole } from "../types";
import { Language, t } from "../i18n";
import {
  Area,
  AreaChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  Cell,
} from "recharts";

interface PublicPortalProps {
  onLogin: (user: User) => void;
  language: Language;
  onLanguageChange: (language: Language) => void;
  themeMode: "system" | "light" | "dark";
  onThemeModeChange: (themeMode: "system" | "light" | "dark") => void;
}

type PortalTab = "signin" | "report" | "tracking";

const STATUS_ORDER = ["SUBMITTED", "UNDER_REVIEW", "INVESTIGATING", "REFERRED", "CLOSED"];

const statusLabel = (s: string) =>
  s === "UNDER_REVIEW" ? "Under Review" : s === "INVESTIGATING" ? "Investigating" : s === "REFERRED" ? "Referred" : s.charAt(0) + s.slice(1).toLowerCase();

const statusColor = (s: string) => {
  if (s === "SUBMITTED") return "text-blue-600 dark:text-blue-400";
  if (s === "UNDER_REVIEW") return "text-indigo-600 dark:text-indigo-400";
  if (s === "INVESTIGATING") return "text-amber-600 dark:text-amber-400";
  if (s === "REFERRED") return "text-purple-600 dark:text-purple-400";
  if (s === "CLOSED") return "text-emerald-600 dark:text-emerald-400";
  if (s === "DISPUTED") return "text-rose-600 dark:text-rose-400";
  return "text-slate-600 dark:text-slate-400";
};

const ACCEPTED_MIME = "image/jpeg,image/png,image/gif,image/webp,audio/mpeg,audio/wav,audio/ogg,video/mp4,video/quicktime,video/x-msvideo,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/plain";

function formatBytes(bytes: number) {
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + " KB";
  return (bytes / 1048576).toFixed(1) + " MB";
}

function generateWhistleblowerPDF(trackedCase: any, stage: any, idx: number) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>ZACC Stage Report – ${trackedCase.reference_code}</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box;}
    body{font-family:Arial,sans-serif;color:#111;padding:48px;background:#fff;position:relative;}
    .watermark{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-45deg);font-size:72px;color:rgba(0,0,0,0.04);pointer-events:none;white-space:nowrap;font-weight:900;letter-spacing:4px;}
    .header{border-bottom:3px solid #059669;padding-bottom:20px;margin-bottom:32px;}
    .header h1{font-size:22px;font-weight:900;color:#059669;letter-spacing:2px;text-transform:uppercase;}
    .header h2{font-size:15px;color:#444;margin-top:4px;}
    .confid{font-size:11px;font-weight:700;color:#e11d48;letter-spacing:3px;text-transform:uppercase;margin-top:6px;}
    .section{margin-bottom:28px;}
    .label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#666;margin-bottom:4px;}
    .value{font-size:14px;color:#111;}
    .notes-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;font-size:13px;line-height:1.6;margin-top:6px;}
    .row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:24px;margin-bottom:24px;}
    .footer{margin-top:48px;border-top:1px solid #e2e8f0;padding-top:16px;font-size:11px;color:#888;text-align:center;}
    @media print{.no-print{display:none;}}
  </style>
</head>
<body>
<div class="watermark">CONFIDENTIAL</div>
<div class="header">
  <h1>Zimbabwe Anti-Corruption Commission</h1>
  <h2>Case Stage Report</h2>
  <div class="confid">Confidential – For Official Use Only</div>
</div>
<div class="row">
  <div><div class="label">Case Reference</div><div class="value" style="font-weight:700;color:#059669;">${trackedCase.reference_code}</div></div>
  <div><div class="label">Case ID</div><div class="value">${trackedCase.case_id}</div></div>
  <div><div class="label">Report Generated</div><div class="value">${new Date().toLocaleString()}</div></div>
</div>
<div class="row">
  <div><div class="label">Stage</div><div class="value" style="font-weight:700;">${statusLabel(stage.stage)}</div></div>
  <div><div class="label">Stage Recorded</div><div class="value">${new Date(stage.created_at).toLocaleString()}</div></div>
  <div><div class="label">Assessment Score</div><div class="value">${stage.final_score ?? "—"} / 100</div></div>
</div>
<div class="section">
  <div class="label">Stage Notes</div>
  <div class="notes-box">${stage.investigator_notes || "No notes recorded."}</div>
</div>
<p style="font-size:11px;color:#999;margin-top:8px;">Note: Investigator identity is withheld to protect the integrity of the investigation process.</p>
<div class="footer">Generated by ZACC Integrity Management System · ${new Date().toLocaleDateString()} · Document #${trackedCase.case_id}-STAGE-${idx + 1}</div>
<script>window.onload=()=>setTimeout(()=>window.print(),400);</script>
</body>
</html>`;
  win.document.write(html);
  win.document.close();
}

export const PublicPortal: React.FC<PublicPortalProps> = ({
  onLogin,
  language,
  onLanguageChange,
  themeMode,
  onThemeModeChange,
}) => {
  const [tab, setTab] = useState<PortalTab>("report");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Sign in state
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // Report form state
  const [formData, setFormData] = useState({
    type: "Bribery",
    institution: "",
    location: "",
    description: "",
  });
  const [submitted, setSubmitted] = useState<any | null>(null);
  const [publicStats, setPublicStats] = useState<any | null>(null);

  // Initial report evidence (optional on first submission)
  const [reportFiles, setReportFiles] = useState<File[]>([]);
  const [reportFileError, setReportFileError] = useState<string | null>(null);
  const [reportUploadNotice, setReportUploadNotice] = useState<string | null>(null);
  const [reportSubmittedEvidenceCount, setReportSubmittedEvidenceCount] = useState(0);
  const reportFileInputRef = useRef<HTMLInputElement>(null);

  // Tracking state
  const [trackingCode, setTrackingCode] = useState("");
  const [trackedCase, setTrackedCase] = useState<any | null>(null);

  // Evidence upload state
  const [evidenceFiles, setEvidenceFiles] = useState<File[]>([]);
  const [evidenceUploading, setEvidenceUploading] = useState(false);
  const [evidenceSuccess, setEvidenceSuccess] = useState<string | null>(null);
  const [evidenceError, setEvidenceError] = useState<string | null>(null);
  const evidenceInputRef = useRef<HTMLInputElement>(null);

  // Dispute state
  const [disputeOpen, setDisputeOpen] = useState(false);
  const [disputeReason, setDisputeReason] = useState("");
  const [disputeFiles, setDisputeFiles] = useState<File[]>([]);
  const [disputeSubmitting, setDisputeSubmitting] = useState(false);
  const [disputeSuccess, setDisputeSuccess] = useState(false);
  const [disputeError, setDisputeError] = useState<string | null>(null);
  const disputeInputRef = useRef<HTMLInputElement>(null);

  const resetMessages = () => { setError(null); };

  useEffect(() => {
    const loadStats = async () => {
      try {
        const response = await apiClient.getPublicStats();
        if (response?.success) {
          setPublicStats(response.data);
        }
      } catch {
        // non-blocking visual widget
      }
    };
    loadStats();
  }, []);

  const integritySeries = useMemo(() => {
    const status = publicStats?.by_status || {};
    return [
      { stage: "Submitted", value: status.SUBMITTED || 0 },
      { stage: "Review", value: status.UNDER_REVIEW || 0 },
      { stage: "Investigating", value: status.INVESTIGATING || 0 },
      { stage: "Closed", value: status.CLOSED || 0 },
      { stage: "Disputed", value: status.DISPUTED || 0 },
    ];
  }, [publicStats]);

  const integrityDonut = useMemo(() => {
    if (!publicStats) return [];
    return [
      { name: "Resolved", value: Number(publicStats.resolved_total || 0) },
      { name: "Active", value: Number(publicStats.active_investigations || 0) },
      { name: "Disputed", value: Number(publicStats.by_status?.DISPUTED || 0) },
    ];
  }, [publicStats]);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    resetMessages();
    try {
      const { user } = await apiClient.login(email, password);
      if (user.role === UserRole.WHISTLEBLOWER) {
        setError("Whistleblowers do not log in here. Use the 'Track Case' tab with your tracking code.");
        await apiClient.logout().catch(() => {});
        localStorage.removeItem("nexus_token");
        localStorage.removeItem("nexus_user");
        setLoading(false);
        return;
      }
      onLogin(user);
    } catch (err: any) {
      setError(err.message || "Authentication failed");
    } finally {
      setLoading(false);
    }
  };

  const handleAnonymousSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (formData.description.trim().length < 20) {
      setError("Description must be at least 20 characters.");
      return;
    }
    setLoading(true);
    resetMessages();
    try {
      const selectedEvidenceCount = reportFiles.length;
      const response = await apiClient.createAnonymousReport(formData);
      if (!response.success) throw new Error(response.message || "Failed to submit report");

      let uploadNotice: string | null = null;
      if (reportFiles.length > 0 && response.data?.reference_code) {
        try {
          const uploadResp = await apiClient.uploadEvidence(
            response.data.reference_code,
            reportFiles,
          );
          const uploadedCount = uploadResp?.data?.uploaded?.length ?? reportFiles.length;
          uploadNotice = `${uploadedCount} evidence file${uploadedCount === 1 ? "" : "s"} uploaded with your report.`;
        } catch {
          uploadNotice = "Your report was submitted, but evidence upload failed. You can upload evidence later in Track Case.";
        }
      }

      setReportUploadNotice(uploadNotice);
      setReportSubmittedEvidenceCount(selectedEvidenceCount);
      setSubmitted(response.data);
      setReportFiles([]);
      setReportFileError(null);
      setFormData({ type: "Bribery", institution: "", location: "", description: "" });
    } catch (err: any) {
      setError(err.message || "Failed to submit report");
    } finally {
      setLoading(false);
    }
  };

  const handleReportFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = Array.from(e.target.files || []);
    const remaining = 10 - reportFiles.length;

    if (remaining <= 0) {
      setReportFileError("You can only attach up to 10 files.");
      return;
    }

    const tooLarge = selected.filter((f) => f.size > 10 * 1024 * 1024);
    const valid = selected.filter((f) => f.size <= 10 * 1024 * 1024).slice(0, remaining);

    if (tooLarge.length > 0) {
      setReportFileError(`${tooLarge.length} file(s) exceeded 10MB and were skipped.`);
    } else {
      setReportFileError(null);
    }

    setReportFiles((prev) => [...prev, ...valid].slice(0, 10));
    if (reportFileInputRef.current) reportFileInputRef.current.value = "";
  };

  const removeReportFile = (index: number) => {
    setReportFiles((prev) => prev.filter((_, i) => i !== index));
    setReportFileError(null);
  };

  const handleTrack = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!trackingCode.trim()) return;
    setLoading(true);
    resetMessages();
    setTrackedCase(null);
    setEvidenceFiles([]);
    setEvidenceSuccess(null);
    setEvidenceError(null);
    setDisputeOpen(false);
    setDisputeSuccess(false);
    try {
      const response = await apiClient.trackCase(trackingCode.trim());
      if (!response.success) throw new Error(response.message || "Case not found");
      setTrackedCase(response.data);
    } catch (err: any) {
      setError(err.message || "Unable to track this case");
    } finally {
      setLoading(false);
    }
  };

  const handleEvidenceFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const maxReach = 10 - (trackedCase?.attachments_count ?? 0);
    const valid = files.filter(f => f.size <= 10 * 1024 * 1024).slice(0, maxReach);
    const oversized = files.filter(f => f.size > 10 * 1024 * 1024);
    if (oversized.length > 0) setEvidenceError(`${oversized.length} file(s) exceed the 10MB limit and were excluded.`);
    else setEvidenceError(null);
    setEvidenceFiles(prev => {
      const combined = [...prev, ...valid];
      return combined.slice(0, maxReach);
    });
  };

  const removeEvidenceFile = (index: number) => {
    setEvidenceFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleEvidenceUpload = async () => {
    if (evidenceFiles.length === 0 || !trackedCase) return;
    setEvidenceUploading(true);
    setEvidenceError(null);
    try {
      const response = await apiClient.uploadEvidence(
        trackedCase.reference_code,
        evidenceFiles,
      );
      if (!response.success) throw new Error(response.message || "Upload failed");
      setEvidenceSuccess(`${evidenceFiles.length} file(s) uploaded successfully.`);
      setEvidenceFiles([]);
      setTrackedCase((prev: any) => ({ ...prev, attachments_count: response.data.total_attachments }));
    } catch (err: any) {
      setEvidenceError(err.message || "Failed to upload files");
    } finally {
      setEvidenceUploading(false);
    }
  };

  const handleDisputeFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []).filter(f => f.size <= 10 * 1024 * 1024).slice(0, 10);
    setDisputeFiles(prev => [...prev, ...files].slice(0, 10));
  };

  const handleDisputeSubmit = async () => {
    if (!disputeReason.trim() || disputeReason.trim().length < 10) {
      setDisputeError("Please provide a dispute reason (at least 10 characters).");
      return;
    }
    setDisputeSubmitting(true);
    setDisputeError(null);
    try {
      const response = await apiClient.publicDispute(
        trackedCase.reference_code,
        disputeReason,
        disputeFiles,
      );
      if (!response.success) throw new Error(response.message || "Failed to submit dispute");
      setDisputeSuccess(true);
      setTrackedCase((prev: any) => ({ ...prev, status: "DISPUTED" }));
    } catch (err: any) {
      setDisputeError(err.message || "Failed to submit dispute");
    } finally {
      setDisputeSubmitting(false);
    }
  };

  const activeStatusIdx = STATUS_ORDER.indexOf(trackedCase?.status ?? "SUBMITTED");
  const maxEvidenceReach = 10 - (trackedCase?.attachments_count ?? 0);
  const useWideTabLayout =
    (tab === "report" && !submitted) ||
    tab === "signin" ||
    (tab === "tracking" && !trackedCase);

  const sideInsightPanel = (
    <div className="lg:col-span-2 space-y-4">
      <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-black/20 p-4">
        <div className="flex items-center justify-between mb-3">
          <p className="text-xs font-black uppercase tracking-widest text-slate-500">Integrity Flow</p>
          <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">{publicStats?.resolution_rate ?? 0}%</span>
        </div>
        <div className="h-[180px]">
          <ResponsiveContainer width="100%" height="100%" minWidth={240} minHeight={150}>
            <AreaChart data={integritySeries}>
              <defs>
                <linearGradient id="integrityFlowSidebar" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#10b981" stopOpacity={0.35} />
                  <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                </linearGradient>
              </defs>
              <XAxis dataKey="stage" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} />
              <YAxis hide />
              <Tooltip />
              <Area type="monotone" dataKey="value" stroke="#10b981" strokeWidth={2.5} fill="url(#integrityFlowSidebar)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-black/20 p-4">
        <p className="text-xs font-black uppercase tracking-widest text-slate-500 mb-3">Trust Snapshot</p>
        <div className="h-[180px]">
          <ResponsiveContainer width="100%" height="100%" minWidth={220} minHeight={150}>
            <PieChart>
              <Pie data={integrityDonut} dataKey="value" innerRadius={40} outerRadius={66} paddingAngle={3}>
                <Cell fill="#10b981" />
                <Cell fill="#3b82f6" />
                <Cell fill="#f43f5e" />
              </Pie>
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-[#04060b] dark:to-[#0a0f1a] text-slate-900 dark:text-slate-200 flex flex-col items-center justify-start px-3 sm:px-4 py-6 sm:py-8">
      {/* Settings Bar */}
      <div className="w-full max-w-5xl flex justify-end gap-2 mb-4 sm:mb-5">
        <select value={themeMode} onChange={e => onThemeModeChange(e.target.value as any)}
          className="px-3 py-2 rounded-lg bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 text-xs font-semibold">
          <option value="system">{t(language, "system")}</option>
          <option value="light">{t(language, "light")}</option>
          <option value="dark">{t(language, "dark")}</option>
        </select>
        <select value={language} onChange={e => onLanguageChange(e.target.value as Language)}
          className="px-3 py-2 rounded-lg bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 text-xs font-semibold">
          <option value="en">English</option>
          <option value="sn">Shona</option>
          <option value="nd">Ndebele</option>
          <option value="to">Tonga</option>
        </select>
      </div>

      {/* Logo */}
      <div className="mb-6 sm:mb-8 text-center max-w-xl">
        <div className="w-16 h-16 mx-auto mb-5 bg-gradient-to-br from-emerald-400 to-emerald-600 rounded-2xl flex items-center justify-center text-3xl font-black text-white shadow-lg">Z</div>
        <h1 className="text-4xl md:text-5xl font-black mb-2 bg-gradient-to-r from-emerald-600 to-indigo-600 dark:from-emerald-400 dark:to-indigo-400 bg-clip-text text-transparent">ZACC Portal</h1>
        <p className="text-sm text-slate-600 dark:text-slate-400 font-medium">Secure. Anonymous. Protected.</p>
      </div>

      {!(tab === "report" && !submitted) && (
      <div className="w-full max-w-5xl grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
        <div className="lg:col-span-2 rounded-3xl border border-slate-200 dark:border-white/10 bg-white/90 dark:bg-[#080c18] p-4 sm:p-5">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-black uppercase tracking-widest text-slate-500">Integrity Flow</p>
            <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">
              Resolution Rate: {publicStats?.resolution_rate ?? 0}%
            </span>
          </div>
          <div className="h-[170px] sm:h-[200px]">
            <ResponsiveContainer width="100%" height="100%" minWidth={260} minHeight={150}>
              <AreaChart data={integritySeries}>
                <defs>
                  <linearGradient id="integrityFlow" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.35} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <XAxis dataKey="stage" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis allowDecimals={false} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} width={26} />
                <Tooltip />
                <Area type="monotone" dataKey="value" stroke="#10b981" strokeWidth={2.5} fill="url(#integrityFlow)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
        <div className="rounded-3xl border border-slate-200 dark:border-white/10 bg-white/90 dark:bg-[#080c18] p-4 sm:p-5">
          <p className="text-xs font-black uppercase tracking-widest text-slate-500 mb-3">Trust Snapshot</p>
          <div className="h-[170px] sm:h-[200px]">
            <ResponsiveContainer width="100%" height="100%" minWidth={220} minHeight={150}>
              <PieChart>
                <Pie data={integrityDonut} dataKey="value" innerRadius={38} outerRadius={64} paddingAngle={3}>
                  <Cell fill="#10b981" />
                  <Cell fill="#3b82f6" />
                  <Cell fill="#f43f5e" />
                </Pie>
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
      )}

      {/* Main Card */}
      <div className={`w-full ${useWideTabLayout ? "max-w-6xl" : "max-w-2xl"} rounded-3xl border border-slate-200 dark:border-white/10 bg-white dark:bg-[#080c18] shadow-2xl overflow-hidden`}>
        {/* Tabs */}
        <div className="grid grid-cols-3 border-b border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-black/20">
          {[
            { id: "report", label: "File Report", icon: "📝" },
            { id: "tracking", label: "Track Case", icon: "🔍" },
            { id: "signin", label: "Staff Login", icon: "🔐" },
          ].map(item => (
            <button key={item.id} onClick={() => { setTab(item.id as PortalTab); setError(null); }}
              className={`px-4 py-4 font-bold text-xs uppercase tracking-wider transition-all relative ${tab === item.id ? "text-emerald-600 dark:text-emerald-400 bg-white dark:bg-white/5" : "text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-300"}`}>
              <span className="text-base mb-1 block">{item.icon}</span>
              {item.label}
              {tab === item.id && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-500" />}
            </button>
          ))}
        </div>

        <div className="p-8">
          {error && (
            <div className="mb-6 rounded-2xl border border-rose-300 dark:border-rose-500/30 bg-rose-50 dark:bg-rose-500/10 px-5 py-4 text-rose-700 dark:text-rose-300 text-sm font-medium">
              ⚠️ {error}
            </div>
          )}

          {/* ── STAFF LOGIN ── */}
          {tab === "signin" && (
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 animate-fade-in">
            <form onSubmit={handleLogin} className="space-y-5 lg:col-span-3">
              <div className="rounded-2xl bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 px-5 py-3 text-xs text-amber-700 dark:text-amber-300 font-semibold">
                For ZACC Staff (Admin &amp; Investigators) only. Whistleblowers do not need to log in — use the Track Case tab.
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Email Address</label>
                <input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="staff@zacc.org.zw" required
                  className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 transition-all font-medium" />
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Password</label>
                <input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" required
                  className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 transition-all font-medium" />
              </div>
              <button type="submit" disabled={loading}
                className="w-full rounded-2xl bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-600 hover:to-emerald-700 text-black font-bold py-4 disabled:opacity-50 transition-all text-sm uppercase tracking-widest shadow-lg shadow-emerald-500/20">
                {loading ? "Authenticating..." : "Sign In"}
              </button>
            </form>
            {sideInsightPanel}
            </div>
          )}

          {/* ── FILE REPORT ── */}
          {tab === "report" && !submitted && (
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 animate-fade-in">
            <form onSubmit={handleAnonymousSubmit} className="space-y-5 lg:col-span-3">
              <div className="rounded-2xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 px-5 py-3 text-xs text-emerald-800 dark:text-emerald-300 font-semibold">
                Your identity is fully protected. No personal information is collected. A unique tracking code will be generated for your case.
              </div>
              <div className="grid grid-cols-1 gap-5">
                <div>
                  <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Type of Corruption</label>
                  <select value={formData.type} onChange={e => setFormData({ ...formData, type: e.target.value })}
                    className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white focus:outline-none focus:border-emerald-500 font-medium">
                    <option>Bribery</option><option>Procurement Fraud</option><option>Abuse of Office</option>
                    <option>Embezzlement</option><option>Nepotism</option><option>Other</option>
                  </select>
                </div>
              </div>
              <div className="rounded-xl bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 px-4 py-3 text-xs font-semibold text-slate-600 dark:text-slate-300">
                Case priority is assigned automatically by the expert system after submission.
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Affected Institution</label>
                <input type="text" value={formData.institution} onChange={e => setFormData({ ...formData, institution: e.target.value })}
                  placeholder="Ministry, department, or organization" required
                  className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 font-medium" />
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Location</label>
                <input type="text" value={formData.location} onChange={e => setFormData({ ...formData, location: e.target.value })}
                  placeholder="District or province"
                  className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 font-medium" />
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Detailed Description</label>
                <textarea rows={5} value={formData.description} onChange={e => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Describe the incident in detail. Include dates, names (if known), amounts, witnesses..." required
                  className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 font-medium resize-none" />
                <p className="text-xs text-slate-500 mt-1">{formData.description.length} characters (min 20)</p>
              </div>
              <div>
                <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">
                  Evidence (Optional)
                </label>
                <div
                  onClick={() => reportFileInputRef.current?.click()}
                  className="border-2 border-dashed border-slate-300 dark:border-white/20 rounded-2xl p-4 text-center cursor-pointer hover:border-emerald-400 dark:hover:border-emerald-500/50 transition-all"
                >
                  <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">Click to attach evidence now</p>
                  <p className="text-xs text-slate-500 mt-1">Optional. You can still submit without evidence. Max 10 files, 10MB each.</p>
                </div>
                <input
                  ref={reportFileInputRef}
                  type="file"
                  multiple
                  accept={ACCEPTED_MIME}
                  onChange={handleReportFileChange}
                  className="hidden"
                />

                {reportFileError && (
                  <p className="mt-2 text-xs font-semibold text-rose-600 dark:text-rose-300">⚠️ {reportFileError}</p>
                )}

                {reportFiles.length > 0 && (
                  <div className="mt-3 space-y-2">
                    {reportFiles.map((f, i) => (
                      <div key={`${f.name}-${i}`} className="flex items-center justify-between rounded-xl border border-slate-200 dark:border-white/10 px-3 py-2 bg-slate-50 dark:bg-white/5">
                        <div className="flex items-center gap-2 min-w-0">
                          <span className="text-sm">📎</span>
                          <span className="text-sm text-slate-700 dark:text-slate-300 truncate">{f.name}</span>
                          <span className="text-xs text-slate-500">{formatBytes(f.size)}</span>
                        </div>
                        <button type="button" onClick={() => removeReportFile(i)} className="text-rose-500 text-sm font-bold">Remove</button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <button type="submit" disabled={loading}
                className="w-full rounded-2xl bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-600 hover:to-emerald-700 text-black font-bold py-4 disabled:opacity-50 transition-all text-sm uppercase tracking-widest shadow-lg shadow-emerald-500/20">
                {loading ? "Submitting Securely..." : "Submit Anonymous Report"}
              </button>
            </form>

            {sideInsightPanel}
            </div>
          )}

          {tab === "report" && submitted && (
            <div className="space-y-5 animate-fade-in">
              <div className="rounded-3xl border border-emerald-300 dark:border-emerald-500/30 bg-emerald-50 dark:bg-emerald-500/10 p-6">
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-500 text-white text-2xl flex items-center justify-center font-black flex-shrink-0">✓</div>
                  <div className="flex-1">
                    <p className="font-black text-emerald-700 dark:text-emerald-300 text-lg mb-2">Report Submitted Successfully</p>
                    <p className="text-sm text-emerald-700 dark:text-emerald-300 mb-4">Your anonymous report has been securely logged and encrypted.</p>
                    <div className="bg-white dark:bg-black/30 rounded-2xl p-5 mb-4 border border-emerald-200 dark:border-emerald-500/20">
                      <p className="text-xs font-black text-slate-500 dark:text-slate-400 uppercase tracking-widest mb-2">Your Session Tracking Code</p>
                      <p className="font-mono font-black text-emerald-700 dark:text-emerald-300 text-2xl tracking-widest">{submitted.reference_code}</p>
                    </div>
                    <div className="rounded-xl bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 px-4 py-3 text-xs text-amber-700 dark:text-amber-300 font-semibold">
                      ⚠️ Save this code securely. It is the ONLY way to track your case. No account or email is required.
                    </div>
                  </div>
                </div>
              </div>
              {reportUploadNotice && (
                <div className="rounded-xl border border-emerald-200 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 px-4 py-3 text-sm font-semibold text-emerald-700 dark:text-emerald-300">
                  {reportUploadNotice}
                </div>
              )}
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div className="rounded-xl border border-slate-200 dark:border-white/10 p-4 bg-slate-50 dark:bg-white/5">
                  <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Status</p>
                  <p className="font-black text-blue-600 dark:text-blue-400">SUBMITTED</p>
                </div>
                <div className="rounded-xl border border-slate-200 dark:border-white/10 p-4 bg-slate-50 dark:bg-white/5">
                  <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Evidence</p>
                  <p className="font-black text-slate-900 dark:text-white">{reportSubmittedEvidenceCount} file{reportSubmittedEvidenceCount === 1 ? "" : "s"}</p>
                </div>
              </div>
              <button onClick={() => { setTab("tracking"); setTrackingCode(submitted.reference_code); setSubmitted(null); }}
                className="w-full rounded-2xl border border-emerald-500 text-emerald-600 dark:text-emerald-400 font-bold py-3.5 text-sm uppercase tracking-wider hover:bg-emerald-50 dark:hover:bg-emerald-500/10 transition-all">
                Track This Case Now →
              </button>
              <button onClick={() => { setSubmitted(null); setReportUploadNotice(null); setReportSubmittedEvidenceCount(0); }}
                className="w-full rounded-2xl bg-slate-100 dark:bg-white/5 text-slate-700 dark:text-slate-300 font-bold py-3 text-sm uppercase tracking-wider hover:bg-slate-200 dark:hover:bg-white/10 transition-all">
                Submit Another Report
              </button>
            </div>
          )}

          {/* ── TRACK CASE ── */}
          {tab === "tracking" && (
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 animate-fade-in">
            <div className="space-y-6 lg:col-span-3">
              <form onSubmit={handleTrack} className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1">
                  <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Enter Your Tracking Code</label>
                  <input type="text" value={trackingCode} onChange={e => setTrackingCode(e.target.value.toUpperCase())}
                    placeholder="ZACC-REF-XXXXXXXXX"
                    className="w-full rounded-2xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-5 py-3.5 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 font-mono font-bold tracking-widest uppercase" />
                </div>
                <button type="submit" disabled={loading}
                  className="sm:mt-7 rounded-2xl bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-600 hover:to-emerald-700 text-black font-bold px-6 py-3.5 disabled:opacity-50 transition-all text-sm uppercase tracking-wider whitespace-nowrap shadow-lg shadow-emerald-500/20">
                  {loading ? "Searching..." : "Track Case"}
                </button>
              </form>

              {/* ── TRACKED CASE DASHBOARD ── */}
              {trackedCase && (
                <div className="space-y-6 animate-fade-in">
                  {/* Overview */}
                  <div className="rounded-3xl border border-slate-200 dark:border-white/10 bg-gradient-to-br from-slate-50 to-white dark:from-white/5 dark:to-white/2 p-6">
                    <div className="flex items-start justify-between gap-4 mb-5">
                      <div>
                        <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Case Overview</p>
                        <h3 className="text-xl font-black text-slate-900 dark:text-white">{trackedCase.type}</h3>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">{trackedCase.institution}</p>
                      </div>
                      <span className={`px-3 py-1.5 rounded-full text-xs font-black uppercase tracking-wider border ${trackedCase.status === "DISPUTED" ? "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-500/20" : trackedCase.status === "CLOSED" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20" : "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-200 dark:border-indigo-500/20"}`}>
                        {statusLabel(trackedCase.status)}
                      </span>
                    </div>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm">
                      {[
                        { label: "Case ID", value: trackedCase.case_id },
                        { label: "Reference", value: trackedCase.reference_code },
                        { label: "Priority", value: trackedCase.priority },
                        { label: "Risk Score", value: `${trackedCase.risk_score}%` },
                      ].map(item => (
                        <div key={item.label} className="rounded-xl bg-white dark:bg-black/20 border border-slate-200 dark:border-white/10 p-3">
                          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">{item.label}</p>
                          <p className="font-black text-slate-900 dark:text-white text-sm">{item.value}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Status Timeline */}
                  <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-[#080c18] p-5">
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Case Progress</p>
                    <div className="flex items-center gap-0">
                      {STATUS_ORDER.map((s, i) => {
                        const done = i <= activeStatusIdx && trackedCase.status !== "DISPUTED";
                        const isCurrent = trackedCase.status === "DISPUTED" ? s === "CLOSED" : trackedCase.status === s;
                        return (
                          <React.Fragment key={s}>
                            <div className="flex flex-col items-center flex-1">
                              <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center text-xs font-black ${done ? "bg-emerald-500 border-emerald-500 text-white" : isCurrent ? "border-emerald-500 text-emerald-500 bg-white dark:bg-[#080c18]" : "border-slate-300 dark:border-white/20 text-slate-400"}`}>
                                {done ? "✓" : i + 1}
                              </div>
                              <p className={`text-[9px] font-bold uppercase tracking-wider mt-1.5 text-center leading-tight ${done || isCurrent ? "text-emerald-600 dark:text-emerald-400" : "text-slate-400"}`}>
                                {statusLabel(s)}
                              </p>
                            </div>
                            {i < STATUS_ORDER.length - 1 && (
                              <div className={`h-0.5 flex-1 mb-5 ${i < activeStatusIdx ? "bg-emerald-500" : "bg-slate-200 dark:bg-white/10"}`} />
                            )}
                          </React.Fragment>
                        );
                      })}
                      {trackedCase.status === "DISPUTED" && (
                        <>
                          <div className="h-0.5 flex-1 mb-5 bg-rose-400" />
                          <div className="flex flex-col items-center">
                            <div className="w-8 h-8 rounded-full border-2 bg-rose-500 border-rose-500 text-white flex items-center justify-center text-xs font-black">!</div>
                            <p className="text-[9px] font-bold uppercase tracking-wider mt-1.5 text-rose-500 text-center">Disputed</p>
                          </div>
                        </>
                      )}
                    </div>
                  </div>

                  {/* Investigation Progress */}
                  <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-[#080c18] p-5">
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Investigation Progress</p>
                    {trackedCase.stage_evaluations && trackedCase.stage_evaluations.length > 0 ? (
                      <div className="space-y-3">
                        {trackedCase.stage_evaluations.map((stage: any, idx: number) => (
                          <div key={stage.id} className="rounded-2xl border border-slate-200 dark:border-white/10 p-4 hover:border-emerald-300 dark:hover:border-emerald-500/30 transition-all">
                            <div className="flex items-start justify-between gap-3">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-2">
                                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider border ${statusColor(stage.stage)} bg-current/5`}
                                    style={{ background: "transparent" }}>
                                    <span className={statusColor(stage.stage)}>{statusLabel(stage.stage)}</span>
                                  </span>
                                  <span className="text-xs text-slate-500 dark:text-slate-400">
                                    {new Date(stage.created_at).toLocaleString()}
                                  </span>
                                </div>
                                <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                                  {stage.investigator_notes || "No notes available for this stage."}
                                </p>
                                {stage.final_score != null && (
                                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">Assessment Score: <strong className="text-emerald-600 dark:text-emerald-400">{stage.final_score}/100</strong></p>
                                )}
                              </div>
                              <button onClick={() => generateWhistleblowerPDF(trackedCase, stage, idx)}
                                className="flex-shrink-0 px-3 py-1.5 rounded-lg border border-slate-300 dark:border-white/10 text-[10px] font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 hover:border-emerald-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition-all">
                                PDF Report
                              </button>
                            </div>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="rounded-xl border border-dashed border-slate-300 dark:border-white/10 p-6 text-center">
                        <p className="text-sm text-slate-500">Your case has been received. Investigators will begin the review process shortly.</p>
                      </div>
                    )}
                  </div>

                  {/* Evidence Upload */}
                  {!["CLOSED", "DISPUTED"].includes(trackedCase.status) && (
                    <div className="rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-[#080c18] p-5">
                      <div className="flex items-center justify-between mb-4">
                        <p className="text-xs font-bold text-slate-500 uppercase tracking-widest">Add Evidence</p>
                        <span className="text-xs font-bold text-slate-500 dark:text-slate-400">
                          {trackedCase.attachments_count}/10 files uploaded
                        </span>
                      </div>
                      {evidenceSuccess && (
                        <div className="mb-4 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-300 dark:border-emerald-500/20 px-4 py-3 text-sm text-emerald-700 dark:text-emerald-300 font-semibold">
                          ✓ {evidenceSuccess}
                        </div>
                      )}
                      {evidenceError && (
                        <div className="mb-4 rounded-xl bg-rose-50 dark:bg-rose-500/10 border border-rose-300 dark:border-rose-500/20 px-4 py-3 text-sm text-rose-700 dark:text-rose-300 font-semibold">
                          ⚠️ {evidenceError}
                        </div>
                      )}
                      {maxEvidenceReach > 0 ? (
                        <>
                          <div
                            onClick={() => evidenceInputRef.current?.click()}
                            className="border-2 border-dashed border-slate-300 dark:border-white/20 rounded-2xl p-6 text-center cursor-pointer hover:border-emerald-400 dark:hover:border-emerald-500/50 transition-all group">
                            <p className="text-2xl mb-2">📎</p>
                            <p className="text-sm font-bold text-slate-700 dark:text-slate-300 group-hover:text-emerald-600 dark:group-hover:text-emerald-400">Click to add evidence files</p>
                            <p className="text-xs text-slate-500 mt-1">Photos, videos, audio, documents · Max 10MB per file · Up to {maxEvidenceReach} more file(s)</p>
                          </div>
                          <input ref={evidenceInputRef} type="file" multiple accept={ACCEPTED_MIME}
                            onChange={handleEvidenceFileChange} className="hidden" />
                          {evidenceFiles.length > 0 && (
                            <div className="mt-4 space-y-2">
                              {evidenceFiles.map((f, i) => (
                                <div key={i} className="flex items-center justify-between rounded-xl border border-slate-200 dark:border-white/10 px-4 py-2.5 bg-slate-50 dark:bg-white/5">
                                  <div className="flex items-center gap-3 min-w-0">
                                    <span className="text-base">{f.type.startsWith("image/") ? "🖼️" : f.type.startsWith("video/") ? "🎥" : f.type.startsWith("audio/") ? "🎵" : "📄"}</span>
                                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300 truncate">{f.name}</span>
                                    <span className="text-xs text-slate-500 flex-shrink-0">{formatBytes(f.size)}</span>
                                  </div>
                                  <button onClick={() => removeEvidenceFile(i)}
                                    className="text-rose-500 hover:text-rose-700 text-lg leading-none ml-3 flex-shrink-0">×</button>
                                </div>
                              ))}
                              <button onClick={handleEvidenceUpload} disabled={evidenceUploading}
                                className="w-full mt-2 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-black font-bold text-sm uppercase tracking-wider disabled:opacity-50 transition-all">
                                {evidenceUploading ? "Uploading..." : `Upload ${evidenceFiles.length} File(s)`}
                              </button>
                            </div>
                          )}
                        </>
                      ) : (
                        <p className="text-sm text-slate-500 text-center py-4">Maximum of 10 evidence files reached.</p>
                      )}
                    </div>
                  )}

                  {/* Dispute Section */}
                  {trackedCase.status === "CLOSED" && !disputeSuccess && (
                    <div className="rounded-2xl border border-amber-200 dark:border-amber-500/20 bg-amber-50 dark:bg-amber-500/10 p-5">
                      <p className="text-xs font-bold text-amber-700 dark:text-amber-400 uppercase tracking-widest mb-2">Case Closed</p>
                      {trackedCase.dispute_reason && (
                        <div className="rounded-xl bg-white dark:bg-black/20 border border-amber-200 dark:border-amber-500/20 px-4 py-3 mb-4">
                          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Closure Reason</p>
                          <p className="text-sm text-slate-700 dark:text-slate-300">{trackedCase.dispute_reason}</p>
                        </div>
                      )}
                      <p className="text-sm text-amber-700 dark:text-amber-300 mb-4">If you disagree with this outcome, you may file a formal dispute with supporting evidence and your statement.</p>
                      {!disputeOpen ? (
                        <button onClick={() => setDisputeOpen(true)}
                          className="w-full py-3 rounded-xl bg-amber-500 hover:bg-amber-600 text-white font-bold text-sm uppercase tracking-wider transition-all">
                          Dispute This Decision
                        </button>
                      ) : (
                        <div className="space-y-4 animate-fade-in">
                          {disputeError && (
                            <div className="rounded-xl bg-rose-50 dark:bg-rose-500/10 border border-rose-300 dark:border-rose-500/20 px-4 py-3 text-sm text-rose-700 dark:text-rose-300 font-semibold">
                              ⚠️ {disputeError}
                            </div>
                          )}
                          <div>
                            <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Dispute Statement <span className="text-rose-500">*</span></label>
                            <textarea rows={4} value={disputeReason} onChange={e => setDisputeReason(e.target.value)}
                              placeholder="Explain why you dispute this decision and what additional information supports your case (min 10 characters)..."
                              className="w-full rounded-xl border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-4 py-3 text-slate-900 dark:text-white placeholder:text-slate-500 focus:outline-none focus:border-amber-500 font-medium resize-none" />
                          </div>
                          <div>
                            <label className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">Supporting Evidence (Optional)</label>
                            <div onClick={() => disputeInputRef.current?.click()}
                              className="border-2 border-dashed border-slate-300 dark:border-white/20 rounded-xl p-4 text-center cursor-pointer hover:border-amber-400 transition-all">
                              <p className="text-sm text-slate-600 dark:text-slate-400 font-medium">Click to attach evidence files · Max 10MB each · Up to 10 files</p>
                            </div>
                            <input ref={disputeInputRef} type="file" multiple accept={ACCEPTED_MIME}
                              onChange={handleDisputeFileChange} className="hidden" />
                            {disputeFiles.length > 0 && (
                              <div className="mt-2 space-y-1">
                                {disputeFiles.map((f, i) => (
                                  <div key={i} className="flex items-center justify-between rounded-lg border border-slate-200 dark:border-white/10 px-3 py-2 text-sm">
                                    <span className="text-slate-700 dark:text-slate-300 truncate">{f.name}</span>
                                    <button onClick={() => setDisputeFiles(p => p.filter((_, j) => j !== i))} className="text-rose-500 ml-2 text-xs">Remove</button>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                          <div className="flex gap-3">
                            <button onClick={handleDisputeSubmit} disabled={disputeSubmitting}
                              className="flex-1 py-3 rounded-xl bg-amber-500 hover:bg-amber-600 text-white font-bold text-sm uppercase tracking-wider disabled:opacity-50 transition-all">
                              {disputeSubmitting ? "Submitting..." : "Submit Dispute"}
                            </button>
                            <button onClick={() => setDisputeOpen(false)}
                              className="flex-1 py-3 rounded-xl bg-slate-100 dark:bg-white/5 text-slate-700 dark:text-slate-300 font-bold text-sm uppercase tracking-wider hover:bg-slate-200 dark:hover:bg-white/10 transition-all">
                              Cancel
                            </button>
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Dispute Success */}
                  {trackedCase.status === "DISPUTED" && (
                    <div className="rounded-2xl border border-rose-200 dark:border-rose-500/20 bg-rose-50 dark:bg-rose-500/10 p-5">
                      <p className="text-xs font-bold text-rose-600 dark:text-rose-400 uppercase tracking-widest mb-2">Dispute Filed</p>
                      <p className="text-sm text-rose-700 dark:text-rose-300">Your dispute has been received and is now under review by ZACC management. You will be notified of the outcome.</p>
                    </div>
                  )}
                </div>
              )}
            </div>
            {sideInsightPanel}
            </div>
          )}
        </div>
      </div>

      <div className="mt-8 text-center">
        <p className="text-xs text-slate-500 font-medium uppercase tracking-widest">
          🔒 End-to-end encrypted · Anonymity guaranteed · Zero-knowledge architecture
        </p>
      </div>
    </div>
  );
};
